name: l2lhub
channels:
  - conda-forge
dependencies:
  - h5py==2.9.0
  - matplotlib==3.1.0
  - nitime==0.7
  - xarray==0.14.1
  - numba==0.43.1
  - scikit-image==0.15.0
  - gcsfs==0.4.0
  - oct2py==5.0.2
  - zarr==2.3.1
  - seaborn==0.9.0
  - holoviews==1.12.3
  - datashader==0.7.0
  - hvplot==0.4.0
  - panel==0.5.1
  - tqdm==4.32.1
  - plotly==3.9.0
  - ipywidgets==7.4.2
  - intake==0.5.1
  - prefect==0.6.3
  - mne==0.18.2
  - octave_kernel
  - pip
  - line_profiler
  - cython
  - pip:
    - julia
    - fooof==0.1.3
    - git+https://github.com/neurodsp-tools/neurodsp@ed82caa2d93606d1500de0997dce962b81bc69eb
    - bycycle==0.1.2
    - pactools
    - nwbwidgets
    - git+https://github.com/ahwillia/tensortools@v0.3.0